INSERT INTO USERS VALUES(1, 1.5, '$2a$10$ng2AG44RNSaHp1rU1jrklOdErsG5zFDWFyZKIJv96Sjni.JrfJTDq', 'test');
INSERT INTO AUTHORITY VALUES(1, 'ROLE_SELLER', 1);
INSERT INTO PRODUCTS VALUES(1, 'test', 1);
-- INSERT INTO CAMPAIGNS VALUES(1, 5.2, 5.2, 'test', 5.2, true, 1, 1);
-- INSERT INTO CAMPAIGN_KEYWORDS VALUES (1, 'keyword');